import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarSquareWrapper } from "./components/sidebar-square";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/app-sidebar";
import { Square } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarSquareWrapper>
            <SidebarProvider>
              <AppSidebar />
              <main className="h-full w-full">
                <div className="absolute">
                  <SidebarTrigger />
                </div>
                <main className="h-full bg-red-400 pt-6">{children}</main>
              </main>
            </SidebarProvider>
          </SidebarSquareWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
